spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: todo-list

  datasource:
    url: jdbc:h2:file:~/data/test
    username: sa
    password: password
  h2:
    console:
      enabled: true
